### ISSUE TITLE
Instancing crashing on AMD GPU

### ISSUE THREAD

**Issue by SamCZ** [OICW/NPGR019#1]
Cannot compile vertex instancing shader because on AMD GPU when you have uniform array of structs and the struct contains only one variable it will return error when compiling.

https://github.com/OICW/NPGR019/blob/master/05-Instancing/shaders.h#L140

**Comment by OICW** [comment]
We've discussed this in person and apparently this was a driver issue, IIRC. Anyway, thanks for reporting, I'll probably change it anyway.
